server:
  port: 8002

spring:
  application:
    name: membership-system
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8

logging:
  level:
    com.membership: DEBUG
